# Generated by Django 3.2.13 on 2022-12-24 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_doctors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='dep_imge',
            field=models.ImageField(upload_to='doctors'),
        ),
    ]
