# Generated by Django 3.2.13 on 2022-12-24 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctors',
            old_name='dep_imge',
            new_name='doc_image',
        ),
    ]
